### ISSUE TITLE
Spawn tile treated as a side block

### ISSUE THREAD

**Issue by ROB1N2401** [ROB1N2401/Heartwars#37] opened 2021-05-21 18:00 UTC
When destroying a spawn block, it is added as a side block to the player's inventory. Whether the bonus AP disappears as you place it back on the field, is unclear.

**Comment by Vo1z** [comment] 2021-05-22 01:22
That's not a bug, It's a big ass feature

**Comment by Vo1z** [comment] 2021-05-23 13:49
Issue was resolved in **Dev 51**

**Closed as completed** 2021-05-23 13:50 UTC
Labels: bug
